version: 2

sources:
  - name: superstore_surf
    database: SURFALYTICS_DW_AlexG7
    schema: stg

    tables:
      - name: orders
        descriotion: raw order data
      - name: people
      - name: returns
